# Generated by Django 3.2.6 on 2021-08-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('categorias', models.CharField(choices=[('Cultura y arte', 'Cultura y arte'), ('Historia', 'Historia'), ('Deporte', 'Deporte'), ('Geografía', 'Geografía'), ('Economía', 'Economía'), ('Ciencia y Educación', 'Ciencia y Educación'), ('Entretenimiento', 'Entretenimiento')], max_length=19)),
                ('cant_preguntas', models.IntegerField()),
                ('tiempo', models.IntegerField(help_text='duracion de partida')),
                ('ptaje_requerido', models.IntegerField(help_text='puntaje requerido')),
            ],
        ),
    ]
