# Generated by Django 3.2.6 on 2021-08-30 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='categorias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcuestionarios.categoria'),
        ),
    ]
