# Generated by Django 3.2.6 on 2021-08-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcuestionarios', '0002_auto_20210829_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='ptaje_requerido',
            field=models.IntegerField(help_text='puntaje requerido en % (- de 100%)'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='tiempo',
            field=models.IntegerField(help_text='duracion de partida en minutos'),
        ),
    ]
