# Generated by Django 3.2.6 on 2021-08-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppreguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
